### ISSUE TITLE
Ember 2.8.2 Handlebars.SafeString deprecation warning

### ISSUE THREAD

**Issue by tehmaestro** [jasonmit/ember-i18n-cp-validations#25]
Hi, I get a warning in Ember 2.8.2 that SafeString is deprecated. What do you think about using this polyfill? https://github.com/workmanw/ember-string-ishtmlsafe-polyfill

**Comment by jasonmit** [comment]
What version are you pulling in?  This should already be resolved.

**Comment by tehmaestro** [comment]
I'm on 2.6.1

**Comment by jasonmit** [comment]
It's fixed on latest, try that and reopen if you still see it.

**Comment by tehmaestro** [comment]
Tried 2.7.1, still getting the deprecation, but I just realized it's because I am extending the i18n compiler to return strings, not SafeString objects, which makes `isHTMLSafe(input)` to always return false, so that's why the `nowrap` function gets to check `instanceof Handlebars.SafeString` which throws the deprecation message.

**Comment by jasonmit** [comment]
Mind submitting a PR, can merge and version since this seems like a valid use case

**Comment by tehmaestro** [comment]
https://github.com/jasonmit/ember-i18n-cp-validations/pull/26

**Comment by jasonmit** [comment]
2.7.2 has your patch, thanks
